# Generated by Django 4.1 on 2022-08-11 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_query", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db_query.city",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db_query.district",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db_query.state",
            ),
        ),
    ]
