# Generated by Django 4.1 on 2022-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_query", "0003_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
